-- Found ament_cmake: 2.0.2 (/opt/ros/iron/share/ament_cmake/cmake)
-- Found geometry_msgs: 5.0.0 (/opt/ros/iron/share/geometry_msgs/cmake)
-- Found rosidl_generator_c: 4.0.0 (/opt/ros/iron/share/rosidl_generator_c/cmake)
-- Found rosidl_generator_cpp: 4.0.0 (/opt/ros/iron/share/rosidl_generator_cpp/cmake)
-- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
-- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
-- Found rosidl_default_generators: 1.5.0 (/opt/ros/iron/share/rosidl_default_generators/cmake)
-- Found rosidl_adapter: 4.0.0 (/opt/ros/iron/share/rosidl_adapter/cmake)
[31mCMake Error at /opt/ros/iron/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:57 (message):
  execute_process(/usr/bin/python3.10 -m rosidl_adapter --package-name
  my_interface --arguments-file
  /home/user/ros2_ws/build/my_interface/rosidl_adapter__arguments__my_interface.json
  --output-dir
  /home/user/ros2_ws/build/my_interface/rosidl_adapter/my_interface
  --output-file
  /home/user/ros2_ws/build/my_interface/rosidl_adapter/my_interface.idls)
  returned error code 1:

  Error processing 'geometry_msgs/msg/Point coordinates' of
  'my_interface/Targetcoordinate': 'geometry_msgs/msg/Point'

  Traceback (most recent call last):

    File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/opt/ros/iron/lib/python3.10/site-packages/rosidl_adapter/__main__.py", line 19, in <module>
      sys.exit(main())
    File "/opt/ros/iron/lib/python3.10/site-packages/rosidl_adapter/main.py", line 53, in main
      abs_idl_file = convert_to_idl(
    File "/opt/ros/iron/lib/python3.10/site-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
      return convert_msg_to_idl(
    File "/opt/ros/iron/lib/python3.10/site-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
      msg = parse_message_string(package_name, input_file.stem, content)
    File "/opt/ros/iron/lib/python3.10/site-packages/rosidl_adapter/parser.py", line 521, in parse_message_string
      Type(type_string, context_package_name=pkg_name),
    File "/opt/ros/iron/lib/python3.10/site-packages/rosidl_adapter/parser.py", line 278, in __init__
      super(Type, self).__init__(
    File "/opt/ros/iron/lib/python3.10/site-packages/rosidl_adapter/parser.py", line 191, in __init__
      raise InvalidResourceName(type_string)

  rosidl_adapter.parser.InvalidResourceName: geometry_msgs/msg/Point

Call Stack (most recent call first):
  /opt/ros/iron/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:132 (rosidl_adapt_interfaces)
  CMakeLists.txt:15 (rosidl_generate_interfaces)

[0m
-- Configuring incomplete, errors occurred!
See also "/home/user/ros2_ws/build/my_interface/CMakeFiles/CMakeOutput.log".
gmake: *** [Makefile:815: cmake_check_build_system] Error 1
